name = "website"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
plinth = ">= 0.5.6 and < 1.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
midas_node = ">= 1.4.0 and < 2.0.0"
midas = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 2.1.0 and < 4.0.0"
lustre = ">= 4.6.3 and < 6.0.0"
supa = ">= 2.0.0 and < 3.0.0"
jot = ">= 8.0.0 and < 9.0.0"
midas_sdk = ">= 0.6.0 and < 1.0.0"
mysig = ">= 0.5.0 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"
gleroglero = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
gleam_time = ">= 0.0.0 and < 2.0.0"
gleamx = {path= "../packages/gleamx"}
eyg_ir = {path= "../packages/gleam_ir"}
eyg_interpreter = {path= "../packages/gleam_interpreter"}
eyg_analysis = {path= "../packages/gleam_analysis"}
eyg_client = {path= "../packages/gleam_client"}
morph = {path= "../packages/morph"}
midas_browser = ">= 1.0.0 and < 2.0.0"
gleam_fetch = ">= 1.1.1 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
oas = ">= 7.2.0 and < 8.0.0"
netlify = ">= 1.0.0 and < 2.0.0"
spotless = ">= 3.2.0 and < 4.0.0"
dag_json = ">= 2.0.0 and < 3.0.0"
multiformats = ">= 2.0.3 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
